### ISSUE TITLE
TableView background color works in iOS 7 but not in iOS 8

### ISSUE THREAD

**Issue by brianhmayo** [Augustyniak/RATreeView#129]
There is a bug with iOS in that on an iPad for iOS 8.x the tableView background color is defaulted to white.  The request is to have RATreeView set this in code to clearColor in order to allow the view background color to show through as the background.

**Comment by Augustyniak** [comment]
Hey,

Sorry for the long response time.

Thanks for the report. Described bug is fixed in #151. In fact, RATreeView specifies background color of the underlying scroll view during initialization but it looks that iOS 9 changes that color in `awakeFromNib` method which is called after initialization process is finished. PR #151 overrides background color of the *scroll view* in `awakeFromNib` method so it should work fine now.

I hope it helps.

**Comment by Augustyniak** [comment]
Closing. Feel free to reopen if necessary.
