### ISSUE TITLE
Table cell separator not taking all width iOS9 / iPad 2

### ISSUE THREAD

**Issue by Amr1977** [Augustyniak/RATreeView#137]
Thanks for great job !

Notice in the image that cell separators don't take all width.

Found this issue on iPad 2 / iOS 9.1
Working fine on iOS 8.4

![cell_separator](https://cloud.githubusercontent.com/assets/3415198/11154643/4e76bbf6-8a49-11e5-8abc-3b9bc8f0ec9e.png)

**Comment by Augustyniak** [comment]
Hey,

This is partly because of the changes in iOS 9. Starting from iOS 9 `UITableView` has property `cellLayoutMarginsFollowReadableWidth` that results in left insets when running application on iPad. PR #141 adds this property to the `RATreeView` so that you can set it to know if you want to get rid of right separator insets.

When it comes to the right separator insets. I think that you have to set `UIEdgeInsetsZero` as the value for `separatorInset` property of the `RATreeView`.

I hope that it helps.

**Comment by Amr1977** [comment]
Brolliant !  
That solved my issue :)

Thank you very much @Augustyniak !

**Comment by Augustyniak** [comment]
Nice to hear that! :smile:  

Closing. Feel free to reopen if necessary.
