### ISSUE TITLE
child:ofItem bug in swift

### ISSUE THREAD

**Issue by aisk** [Augustyniak/RATreeView#83]
Hi, I use RATreeView in swift, and found a bug:

    func treeView(treeView: RATreeView!, child index: Int, ofItem item: AnyObject!) -> AnyObject! {
        if item == nil {
            return sportTypes![index]
        }
        let sportType = item as SportType
        return sportType.subSportTypes![index]
    }

This will return the root SportTypes at first level cells. When I click a cell, this function is called and I think the item will be not nil but the parent item, and I can choose child item to return. But actually the item is still nil.
Now I saved the item in didSelectRowForItem, and use this to choose if a child item is clicked for workaround.

**Comment by TechGuyVN** [comment]
can your share your porting code to swift, i can port with no error but title of each cell not display, i have no idea why ?

**Comment by Augustyniak** [comment]
@aisk Sorry that you have to wait for a response so much time. I created an example project in Swift and everything seems to work OK - maybe it was fixed in the newest releases of the application. 

@TechGuyVN I added an example project which is entirely written in Swift. It can be found at https://github.com/Augustyniak/RATreeView/tree/master/Examples. Just run example project and select *RATreeViewBasicExampleSwift* target to run it.

I attached the screenshot that shows how you can change select a target within Xcode project.
<img width="586" alt="napkin 28-11-15 3 18 06 pm" src="https://cloud.githubusercontent.com/assets/4410346/11452297/3aee6124-95e3-11e5-8f35-4d2c559c9eb3.png">

I hope that this helps.

**Comment by aisk** [comment]
@Augustyniak Thanks for resolve it, and sadly this issue lives longer than my project 😂
