### ISSUE TITLE
[iOS7+] Glitch in the default rows collapsing animation

### ISSUE THREAD

**Issue by cavarelli** [Augustyniak/RATreeView#91]
Hey @Augustyniak !

Great job on this library, it really made my day ;)

Just wanted to let you know there is a small glitch with the default row collapsing animation starting with iOS 7. It has to do with the change in design of the table view cells I guess. When collapsing rows, you can see the separator line extending on the left larger than it is supposed to.

To prevent this from happening, I set the row collapsing animation to fade rather than bottom (default).

Here is the code for people who want the quick fix:
```
RATreeView *treeView = [[RATreeView alloc] initWithFrame:self.view.bounds];
...
treeview.rowsCollapsingAnimation = RATreeViewRowAnimationFade;
...
```

**Comment by DRosadoYew** [comment]
Same issue here. Setting the animation to RATreeViewRowAnimationFade does not solve it. It looks like the parameter is being ignored by the framework when inserting or deleting rows.

**Comment by Augustyniak** [comment]
@cavarelli Does this happen for the default separator in `UITableViewCell`. If yes I think that this is due to some problems related to the `UITableView` itself but that doesn't solve your issue. Can you provide me with some project/code that would allow me to replicate your issues? 

@DRosadoYew I don't find any place in which `RATreeView` ignores `rowsCollapsingAnimation` parameter. Can you point that in code os provide me with code/project example?
